version: 2

sources:
  - name: movies_data_prataap
    tables:
      - name: movies_raw
      - name: ratings_raw
      - name: movies_curate
      - name: ratings_curate
      - name: movie_ratings_pres

models:
  - name: movies_curate
    columns:
      - name: adult
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: budget
        tests:
          - not_null
          - is_numeric
      - name: revenue
        tests:
          - not_null
          - is_numeric

  - name: ratings_curate
    columns:
      - name: user_id
        tests:
          - not_null
          - assert_type:
              column_name: user_id
              expected_type: 'NUMERIC'
      - name: movie_id
        tests:
          - not_null
          - assert_type:
              column_name: movie_id
              expected_type: 'NUMERIC'
      - name: rating
        tests:
          - not_null
          - assert_type:
              column_name: rating
              expected_type: 'NUMERIC'
      - name: timestamp
        tests:
          - not_null
          - assert_type:
              column_name: timestamp
              expected_type: 'NUMERIC'
      - name: load_time
        tests:
          - not_null
          - assert_type:
              column_name: load_time
              expected_type: 'TIMESTAMP'

  - name: movie_ratings_pres
    description: "Generate movies rankings by median rating"
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null
      - name: number_of_ratings
        tests:
          - not_null
          - assert_type:
              column_name: number_of_ratings
              expected_type: 'INT64'
      - name: median_rating
        tests:
          - not_null
          - assert_type:
              column_name: median_rating
              expected_type: 'FLOAT64'
      - name: movie_rank
        tests:
          - not_null
          - assert_type:
              column_name: movie_rank
              expected_type: 'INT64'
      - name: bayesian_ranking
        tests:
          - not_null
          - assert_type:
              column_name: bayesian_ranking
              expected_type: 'FLOAT64'