project_id = 'ee-india-se-data'
dataset_id = 'movies_data_prataap'
movies_table_name = 'movies_raw'
ratings_table_name = 'ratings_raw'
movies_table_ref = f'{project_id}.{dataset_id}.{movies_table_name}'
ratings_table_ref = f'{project_id}.{dataset_id}.{ratings_table_name}'
