version: 2

sources:
  - name: movies_data_prataap
    tables:
      - name: movies_raw

models:
  - name: movies_raw_to_curate
    columns:
      - name: adult
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: budget
        tests:
          - not_null
          - is_numeric
      - name: revenue
        tests:
          - not_null
          - is_numeric
