name: Deploy Cloud Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy process-movies-data-function \
          --runtime python39 \
          --trigger-bucket ${{ secrets.GCP_LANDING_BUCKET }} \
          --entry-point main \
          --set-env-vars BIGQUERY_DATASET=${{ secrets.BIGQUERY_SCHEMA }},BIGQUERY_MOVIES_TABLE=${{ secrets.BIGQUERY_MOVIES_TABLE }} \
          --region us-central1